-- =============================================================
-- seed.sql — one clearly labelled demo project.
--
-- Every row it creates has is_demo = true, so removal is a single
-- predicate. See scripts/unseed.ts or:
--   delete from projects where is_demo;   -- cascades to children
--
-- Ownership: uses the first auth.users row if one exists, otherwise
-- the documented placeholder below. Run scripts/claim-ownership.ts
-- after you sign in to the dashboard to reassign rows to your real
-- account.
-- =============================================================

do $$
declare
  v_owner      uuid := coalesce(
                         (select id from auth.users order by created_at limit 1),
                         '00000000-0000-0000-0000-0000000000aa'::uuid);
  v_project    uuid;
  v_agent      uuid;
  v_task_res   uuid;
  v_task_brief uuid;
  v_artifact   uuid;
  v_job_done   uuid;
  v_job_failed uuid;
  v_job_gated  uuid;
begin
  if exists (select 1 from projects where is_demo) then
    raise notice 'Demo data already present; nothing seeded.';
    return;
  end if;

  -- ---- project ----------------------------------------------
  insert into projects (owner_id, name, slug, description, status, priority, tags,
                        canonical_location, location_kind, is_demo)
  values (v_owner,
          'DEMO — System Shakedown',
          'demo-system-shakedown',
          'Clearly labelled demo project used to prove the research → evidence → draft → approval → filing path end to end. Safe to delete.',
          'active', 'medium', array['demo','shakedown'],
          '/Users/you/omnios-workspace/demo-system-shakedown', 'local_path', true)
  returning id into v_project;

  -- ---- agent -------------------------------------------------
  -- allowed_actions is an explicit whitelist. Note that send_message
  -- is included: the agent is allowed to ATTEMPT it, and policy is
  -- what stops it from happening without approval.
  insert into agents (owner_id, name, role, runtime_type, status,
                      allowed_actions, allowed_project_scope,
                      configuration_reference, last_seen_at, is_demo)
  values (v_owner,
          'mac-local-runner',
          'Local research and drafting runner',
          'local', 'idle',
          array['read_source','read_project_files','query_system','research_topic',
                'capture_evidence','create_artifact','organize_project_files',
                'update_task_status','update_job_status','create_task',
                'draft_message','draft_report','send_message'],
          array[]::uuid[],                       -- empty = all of this owner's projects
          'local-agent/src/agents/mac-local-runner.ts',
          now(), true)
  returning id into v_agent;

  -- ---- tasks -------------------------------------------------
  insert into tasks (owner_id, project_id, title, description, status, priority,
                     assigned_agent_id, is_demo)
  values (v_owner, v_project,
          'Research: how the approval gate should behave',
          'Collect sources on human-in-the-loop controls for agent systems and record them as evidence.',
          'done', 'medium', v_agent, true)
  returning id into v_task_res;

  insert into tasks (owner_id, project_id, title, description, status, priority,
                     assigned_agent_id, is_demo)
  values (v_owner, v_project,
          'Draft the summary note for review',
          'Turn the captured evidence into a short reviewable brief. Do not send anything.',
          'awaiting_approval', 'high', v_agent, true)
  returning id into v_task_brief;

  insert into tasks (owner_id, project_id, title, description, status, priority, is_demo)
  values (v_owner, v_project,
          'Decide whether to promote draft_pull_request to automatic',
          'Review successful runs first. Promotion is itself an approval_required action.',
          'backlog', 'low', true);

  -- ---- artifact (the output of the finished job) -------------
  insert into artifacts (owner_id, project_id, task_id, name, artifact_type,
                         location_kind, inline_body, created_by, version,
                         metadata, is_demo)
  values (v_owner, v_project, v_task_res,
          'Demo research brief — human-in-the-loop controls',
          'report', 'inline',
          E'# Demo research brief\n\nPreliminary, generated by the demo workflow.\n\n- Consequential agent actions should be previewed exactly, then approved.\n- An unanswered approval must expire rather than execute late.\n- The audit trail should record request, decision, and execution separately.\n\nStatus: draft for review. Not sent anywhere.',
          'mac-local-runner', 1,
          jsonb_build_object('generated_by', 'demo-workflow', 'review_status', 'draft_for_review'),
          true)
  returning id into v_artifact;

  -- ---- evidence ----------------------------------------------
  insert into evidence (owner_id, project_id, task_id, artifact_id, title, source_url,
                        publisher, excerpt, relevance_note, verification, confidence, is_demo)
  values
    (v_owner, v_project, v_task_res, v_artifact,
     'Human oversight of automated decisions',
     'https://www.nist.gov/itl/ai-risk-management-framework',
     'NIST',
     'Risk management for AI systems emphasises documented oversight, traceability, and accountability.',
     'Supports requiring an explicit human decision on consequential actions.',
     'primary_source', 0.80, true),
    (v_owner, v_project, v_task_res, v_artifact,
     'Least-privilege access control',
     'https://csrc.nist.gov/glossary/term/least_privilege',
     'NIST CSRC',
     'Each subject should be granted the most restrictive set of privileges needed to perform its task.',
     'Basis for per-agent allowed_actions rather than a single all-powerful agent.',
     'primary_source', 0.85, true);

  -- ---- jobs --------------------------------------------------
  -- 1. A completed internal_write job with a linked output.
  insert into jobs (owner_id, project_id, task_id, agent_id, job_type, input_reference,
                    status, attempt_count, queued_at, claimed_at, started_at, finished_at,
                    output_artifact_id, idempotency_key, is_demo)
  values (v_owner, v_project, v_task_res, v_agent, 'research_topic',
          jsonb_build_object('topic', 'human-in-the-loop controls for agent systems'),
          'completed', 1,
          now() - interval '42 minutes', now() - interval '41 minutes',
          now() - interval '41 minutes', now() - interval '38 minutes',
          v_artifact, 'demo:research:human-in-the-loop:v1', true)
  returning id into v_job_done;

  -- 2. A failed job, so error display can be checked.
  insert into jobs (owner_id, project_id, task_id, agent_id, job_type, input_reference,
                    status, attempt_count, queued_at, started_at, finished_at,
                    error_summary, idempotency_key, is_demo)
  values (v_owner, v_project, v_task_res, v_agent, 'read_source',
          jsonb_build_object('url', 'https://example.invalid/unreachable'),
          'failed', 3,
          now() - interval '30 minutes', now() - interval '29 minutes', now() - interval '29 minutes',
          'DNS lookup failed for example.invalid after 3 attempts. Source skipped; no evidence recorded.',
          'demo:read:example-invalid:v1', true)
  returning id into v_job_failed;

  -- 3. The gated job: a consequential action, parked, NOT executed.
  insert into jobs (owner_id, project_id, task_id, agent_id, job_type, input_reference,
                    status, attempt_count, queued_at, claimed_at,
                    idempotency_key, is_demo)
  values (v_owner, v_project, v_task_brief, v_agent, 'send_message',
          jsonb_build_object('channel', 'email', 'to', 'consultant@example.com',
                             'subject', 'DEMO — draft only, nothing was sent'),
          'awaiting_approval', 1,
          now() - interval '12 minutes', now() - interval '11 minutes',
          'demo:send:brief-to-consultant:v1', true)
  returning id into v_job_gated;

  -- ---- approvals ---------------------------------------------
  -- Pending: the exact action, in full, awaiting your decision.
  insert into approvals (owner_id, project_id, requested_by_agent_id, job_id, action_type,
                         action_preview, action_payload, target_reference, risk_level,
                         status, expires_at, is_demo)
  values (v_owner, v_project, v_agent, v_job_gated, 'send_message',
          E'Send an email to consultant@example.com.\n\nSubject: DEMO — draft only, nothing was sent\n\nBody:\n  Hello,\n  Attached is the preliminary demo brief for review. All figures are\n  synthetic and no decision has been taken.\n\nAttachment: "Demo research brief — human-in-the-loop controls" (inline artifact)\n\nNothing has been sent. Approving this request would perform the send exactly as shown above.',
          jsonb_build_object('channel','email','to','consultant@example.com',
                             'subject','DEMO — draft only, nothing was sent',
                             'attachment_artifact_id', v_artifact),
          'email:consultant@example.com', 'approval_required',
          'pending', now() + interval '7 days', true);

  -- Denied, with a note: shows the decision trail on the other branch.
  insert into approvals (owner_id, project_id, requested_by_agent_id, job_id, action_type,
                         action_preview, action_payload, target_reference, risk_level,
                         status, decided_at, decided_by_actor_type, decision_note,
                         expires_at, is_demo)
  values (v_owner, v_project, v_agent, null, 'deploy',
          'Deploy the dashboard to Vercel production.',
          jsonb_build_object('target','vercel','environment','production'),
          'vercel:omnios-dashboard:production', 'approval_required',
          'denied', now() - interval '5 minutes', 'user',
          'Not yet — validate locally first.',
          now() + interval '7 days', true);

  raise notice 'Seeded demo project % (owner %).', v_project, v_owner;
end;
$$;
