import { PolicyRefusal, Runner } from '../runner.js';
import { adapters } from '@omnios/shared';

/**
 * The demonstrator: research → evidence → draft → approval → filing.
 *
 * Deliberately offline. The "research" step reads a fixed local source
 * set rather than the live web, so the demo is deterministic, sends
 * nothing, and proves the plumbing rather than the retrieval. Swap
 * `gatherSources` for a real search call once the plumbing is trusted.
 */

interface Source {
  title: string;
  url: string;
  publisher: string;
  excerpt: string;
  relevance: string;
  confidence: number;
}

function gatherSources(topic: string): Source[] {
  return [
    {
      title: 'Human oversight of automated decisions',
      url: 'https://www.nist.gov/itl/ai-risk-management-framework',
      publisher: 'NIST',
      excerpt:
        'Risk management for AI systems emphasises documented oversight, traceability, and accountability.',
      relevance: `Supports requiring an explicit human decision on consequential actions while researching "${topic}".`,
      confidence: 0.8,
    },
    {
      title: 'Least privilege',
      url: 'https://csrc.nist.gov/glossary/term/least_privilege',
      publisher: 'NIST CSRC',
      excerpt:
        'Each subject should be granted the most restrictive set of privileges needed to perform its task.',
      relevance: 'Basis for per-agent allowed_actions instead of one all-powerful agent.',
      confidence: 0.85,
    },
  ];
}

function writeDraft(topic: string, sources: Source[]): string {
  const lines = [
    `# Draft brief — ${topic}`,
    '',
    '> Status: DRAFT FOR REVIEW. Generated by the local agent runner. Nothing has been sent.',
    '',
    '## What the sources support',
    ...sources.map((s) => `- ${s.excerpt} (${s.publisher})`),
    '',
    '## Why it matters here',
    ...sources.map((s) => `- ${s.relevance}`),
    '',
    '## Evidence trail',
    ...sources.map((s) => `- ${s.title} — ${s.publisher} — ${s.url}`),
    '',
    '## Assumptions and gaps',
    '- The research step in this demo reads a fixed source set, not the live web.',
    '- No claim here has been independently verified by a second source.',
  ];
  return lines.join('\n');
}

export interface DemoResult {
  projectId: string;
  taskId: string;
  researchJobId: string;
  draftJobId: string;
  sendJobId: string;
  artifactId: string;
  evidenceIds: string[];
  approvalId: string;
  /** True when the idempotency key matched finished work and nothing was redone. */
  alreadyComplete?: boolean;
}

export async function runResearchToApprovalDemo(
  runner: Runner,
  topic = 'human-in-the-loop controls for agent systems',
): Promise<DemoResult> {
  const ownerId = await runner.resolveOwnerId();
  const projectId = await runner.ensureProject(
    'demo-system-shakedown',
    'DEMO — System Shakedown',
    ownerId,
  );

  console.log(`\n▸ Demo workflow${runner.isDryRun ? ' (DRY RUN — no writes)' : ''}`);
  console.log(`  topic: ${topic}`);
  console.log(`  autonomy: emergency_pause=${runner.emergencyPause}\n`);

  // ---- 1. research (internal_write, automatic) ------------------
  const task = await runner.createTask({
    ownerId,
    projectId,
    title: `Research: ${topic}`,
    description: 'Collect sources, record evidence, draft a reviewable brief. Send nothing.',
    status: 'in_progress',
  });

  const research = await runner.queueJob({
    ownerId,
    projectId,
    taskId: task,
    jobType: 'research_topic',
    payload: { topic },
  });

  // Idempotency has to be honoured, not merely recorded. On a second
  // run with the same topic these jobs already exist and are finished;
  // the first version drove them forward anyway and the database
  // correctly refused the illegal transition out of 'completed'.
  if (research.reused && Runner.isFinished(research.status)) {
    console.log(`  this exact topic has already been run (job ${research.id} is ${research.status}).`);
    console.log('  nothing to redo — vary the topic to run it again:');
    console.log('    npm run agent -- run-demo "some other question"\n');
    return {
      projectId,
      taskId: task,
      researchJobId: research.id,
      draftJobId: '(skipped — already done)',
      sendJobId: '(skipped — already done)',
      artifactId: '(skipped — already done)',
      evidenceIds: [],
      approvalId: '(see the approvals view)',
      alreadyComplete: true,
    };
  }

  await runner.claim(research.id);
  await runner.setJobStatus(research.id, 'running', { attempt_count: 1 });
  await runner.log(research.id, 'info', 'research', `Gathering sources for "${topic}".`, {}, ownerId);

  const sources = gatherSources(topic);

  // ---- 2. evidence (internal_write, automatic) ------------------
  const evidenceIds: string[] = [];
  for (const s of sources) {
    const id = await runner.saveEvidence({
      ownerId,
      projectId,
      taskId: task,
      jobId: research.id,
      title: s.title,
      sourceUrl: s.url,
      publisher: s.publisher,
      excerpt: s.excerpt,
      relevanceNote: s.relevance,
      verification: 'primary_source',
      confidence: s.confidence,
    });
    evidenceIds.push(id);
    await runner.log(research.id, 'info', 'evidence', `Recorded: ${s.title}`, { url: s.url }, ownerId);
  }
  await runner.setJobStatus(research.id, 'completed');

  // ---- 3. draft (external_draft, automatic — prepared, not sent) -
  const draft = await runner.queueJob({
    ownerId,
    projectId,
    taskId: task,
    jobType: 'draft_report',
    payload: { topic, sourceCount: sources.length },
  });
  await runner.claim(draft.id);
  await runner.setJobStatus(draft.id, 'running', { attempt_count: 1 });

  const body = writeDraft(topic, sources);
  const artifactId = await runner.saveArtifact({
    ownerId,
    projectId,
    taskId: task,
    name: `Draft brief — ${topic}`,
    artifactType: 'report',
    body,
    metadata: { evidence_count: evidenceIds.length, generated_by: 'research-to-approval demo' },
  });
  await runner.log(draft.id, 'info', 'draft', 'Saved draft brief as a project artifact.', { artifactId }, ownerId);
  await runner.setJobStatus(draft.id, 'completed', { output_artifact_id: runner.isDryRun ? null : artifactId });

  // ---- 4. the consequential step: STOP and ask -------------------
  const send = await runner.queueJob({
    ownerId,
    projectId,
    taskId: task,
    jobType: 'send_message',
    payload: {
      channel: 'email',
      to: 'consultant@example.com',
      subject: `Draft brief for review — ${topic}`,
    },
  });
  await runner.claim(send.id);

  const decision = runner.check('send_message');
  console.log(`  policy check "send_message" → ${decision.outcome}: ${decision.reason}`);

  let approvalId = '';
  if (decision.outcome === 'allow') {
    // Not reachable under the current policy. If it ever is, that means
    // send_message was deliberately promoted — so say so loudly.
    throw new Error(
      'OMNIOS_UNEXPECTED_AUTONOMY: send_message is auto_allowed. The demo refuses to actually send anything.',
    );
  }

  if (decision.outcome === 'needs_approval') {
    const preview = adapters.outlook.preview({
      actionType: 'send_message',
      target: 'consultant@example.com',
      payload: {
        to: 'consultant@example.com',
        subject: `Draft brief for review — ${topic}`,
        body:
          `Hello,\n\nAttached is a preliminary draft brief on ${topic}. ` +
          `It is generated from ${sources.length} recorded sources and has not been reviewed.\n\nRegards`,
        attachment_artifact_id: artifactId,
      },
    });

    approvalId = await runner.requestApproval({
      ownerId,
      projectId,
      jobId: send.id,
      actionType: 'send_message',
      preview: preview.preview,
      payload: preview.payload,
      target: preview.target,
    });

    await runner.log(
      send.id,
      'warn',
      'approval',
      'Consequential action parked. Nothing was sent. Awaiting a human decision.',
      { approvalId },
      ownerId,
    );
  }

  // Prove the adapter itself also refuses, not just the policy layer.
  try {
    await adapters.outlook.execute({
      actionType: 'send_message',
      target: 'consultant@example.com',
      payload: {},
    });
    throw new Error('OMNIOS_ADAPTER_SHOULD_HAVE_REFUSED');
  } catch (err) {
    if (err instanceof Error && err.name === 'AdapterDisabledError') {
      console.log(`  adapter check → refused as expected: ${err.message.split(':')[0]}`);
    } else {
      throw err;
    }
  }

  console.log('\n▸ Result');
  console.log('  research job    : completed');
  console.log('  draft job       : completed, artifact filed against the project');
  console.log('  send job        : awaiting_approval — NOT executed');
  console.log(`  approval        : ${approvalId || '(dry run)'}`);
  console.log('  open the dashboard → Approvals to decide.\n');

  return {
    projectId,
    taskId: task,
    researchJobId: research.id,
    draftJobId: draft.id,
    sendJobId: send.id,
    artifactId,
    evidenceIds,
    approvalId,
  };
}

/** Demonstrates that a refusal is a refusal, not a workaround. */
export async function demonstrateRefusals(runner: Runner): Promise<void> {
  console.log('\n▸ Refusal checks');

  for (const actionType of ['exfiltrate_secrets', 'disable_audit', 'invent_new_power']) {
    const d = runner.check(actionType);
    console.log(`  ${actionType.padEnd(20)} → ${d.outcome}: ${d.reason}`);
  }

  try {
    runner.safePath('../../etc/passwd');
    console.log('  path escape          → NOT BLOCKED (this is a bug)');
  } catch (err) {
    console.log(`  path escape          → blocked: ${(err as Error).name}`);
  }

  try {
    runner.requireAllowed('disable_audit');
  } catch (err) {
    if (err instanceof PolicyRefusal) {
      console.log(`  requireAllowed       → threw PolicyRefusal as expected`);
    } else {
      throw err;
    }
  }
  console.log('');
}
